model:
  d_inp: 1024
  d_model: 128
data:
  num_workers: 2
  paths:
    interim: 'data/interim/'
    youtube8M: 'data/interim/youtube8M/selected_features'

hparams:
  lr: 0.0001
  weight_decay: 0.0005
  ratio_s:  0
  ratio_k1: 0.1
  alpha: 0.5
  num_frames: 200
  batch_size: 128
  n_layer: 4
  n_head: 8
  use_unq: True
  use_unif: False
setup:
  wandb_name: video-sum

lightning:
  trainer:
    max_epochs: 40
    log_every_n_steps: 100

is_raw: False
